export const districts = [
  // Ahuachapán
  { value: "01", label: "AHUACHAPÁN", departmentId: "01" },
  { value: "02", label: "APANECA", departmentId: "01" },
  { value: "03", label: "ATIQUIZAYA", departmentId: "01" },
  { value: "04", label: "CONCEPCIÓN DE ATACO", departmentId: "01" },
  { value: "05", label: "EL REFUGIO", departmentId: "01" },
  { value: "06", label: "GUAYMANGO", departmentId: "01" },
  { value: "07", label: "JUJUTLA", departmentId: "01" },
  { value: "08", label: "SAN FRANCISCO MENÉNDEZ", departmentId: "01" },
  { value: "09", label: "SAN LORENZO", departmentId: "01" },
  { value: "10", label: "SAN PEDRO PUXTLA", departmentId: "01" },
  { value: "11", label: "TACUBA", departmentId: "01" },
  { value: "12", label: "TURÍN", departmentId: "01" },
  // Santa Ana
  { value: "01", label: "CANDELARIA DE LA FRONTERA", departmentId: "02" },
  { value: "02", label: "COATEPEQUE", departmentId: "02" },
  { value: "03", label: "CHALCHUAPA", departmentId: "02" },
  { value: "04", label: "EL CONGO", departmentId: "02" },
  { value: "05", label: "EL PORVENIR", departmentId: "02" },
  { value: "06", label: "MASAHUAT", departmentId: "02" },
  { value: "07", label: "METAPÁN", departmentId: "02" },
  { value: "08", label: "SAN ANTONIO PAJONAL", departmentId: "02" },
  { value: "09", label: "SAN SEBASTIÁN SALITRILLO", departmentId: "02" },
  { value: "10", label: "SANTA ANA", departmentId: "02" },
  { value: "11", label: "STA ROSA GUACHI", departmentId: "02" },
  { value: "12", label: "STGO D LA FRONT", departmentId: "02" },
  { value: "13", label: "TEXISTEPEQUE", departmentId: "02" },
  // Sonsonate
  { value: "01", label: "ACAJUTLA", departmentId: "03" },
  { value: "02", label: "ARMENIA", departmentId: "03" },
  { value: "03", label: "CALUCO", departmentId: "03" },
  { value: "04", label: "CUISNAHUAT", departmentId: "03" },
  { value: "05", label: "STA I ISHUATAN", departmentId: "03" },
  { value: "06", label: "IZALCO", departmentId: "03" },
  { value: "07", label: "JUAYÚA", departmentId: "03" },
  { value: "08", label: "NAHUIZALCO", departmentId: "03" },
  { value: "09", label: "NAHULINGO", departmentId: "03" },
  { value: "10", label: "SALCOATITÁN", departmentId: "03" },
  { value: "11", label: "SAN ANTONIO DEL MONTE", departmentId: "03" },
  { value: "12", label: "SAN JULIÁN", departmentId: "03" },
  { value: "13", label: "STA C MASAHUAT", departmentId: "03" },
  { value: "14", label: "SANTO DOMINGO GUZMÁN", departmentId: "03" },
  { value: "15", label: "SONSONATE", departmentId: "03" },
  { value: "16", label: "SONZACATE", departmentId: "03" },
  // Chalatenango
  { value: "01", label: "AGUA CALIENTE", departmentId: "04" },
  { value: "02", label: "ARCATAO", departmentId: "04" },
  { value: "03", label: "AZACUALPA", departmentId: "04" },
  { value: "04", label: "CITALÁ", departmentId: "04" },
  { value: "05", label: "COMALAPA", departmentId: "04" },
  { value: "06", label: "CONCEPCIÓN QUEZALTEPEQUE", departmentId: "04" },
  { value: "07", label: "CHALATENANGO", departmentId: "04" },
  { value: "08", label: "DULCE NOM MARÍA", departmentId: "04" },
  { value: "09", label: "EL CARRIZAL", departmentId: "04" },
  { value: "10", label: "EL PARAÍSO", departmentId: "04" },
  { value: "11", label: "LA LAGUNA", departmentId: "04" },
  { value: "12", label: "LA PALMA", departmentId: "04" },
  { value: "13", label: "LA REINA", departmentId: "04" },
  { value: "14", label: "LAS VUELTAS", departmentId: "04" },
  { value: "15", label: "NOMBRE DE JESUS", departmentId: "04" },
  { value: "16", label: "NVA CONCEPCIÓN", departmentId: "04" },
  { value: "17", label: "NUEVA TRINIDAD", departmentId: "04" },
  { value: "18", label: "OJOS DE AGUA", departmentId: "04" },
  { value: "19", label: "POTONICO", departmentId: "04" },
  { value: "20", label: "SAN ANT LA CRUZ", departmentId: "04" },
  { value: "21", label: "SAN ANT RANCHOS", departmentId: "04" },
  { value: "22", label: "SAN FERNANDO", departmentId: "04" },
  { value: "23", label: "SAN FRANCISCO LEMPA", departmentId: "04" },
  { value: "24", label: "SAN FRANCISCO MORAZÁN", departmentId: "04" },
  { value: "25", label: "SAN IGNACIO", departmentId: "04" },
  { value: "26", label: "SAN I LABRADOR", departmentId: "04" },
  { value: "27", label: "SAN J CANCASQUE", departmentId: "04" },
  { value: "28", label: "SAN JOSE FLORES", departmentId: "04" },
  { value: "29", label: "SAN LUIS CARMEN", departmentId: "04" },
  { value: "30", label: "SN MIG MERCEDES", departmentId: "04" },
  { value: "31", label: "SAN RAFAEL", departmentId: "04" },
  { value: "32", label: "SANTA RITA", departmentId: "04" },
  { value: "33", label: "TEJUTLA", departmentId: "04" },
  // La Libertad
  { value: "01", label: "ANTGO CUSCATLÁN", departmentId: "05" },
  { value: "02", label: "CIUDAD ARCE", departmentId: "05" },
  { value: "03", label: "COLON", departmentId: "05" },
  { value: "04", label: "COMASAGUA", departmentId: "05" },
  { value: "05", label: "CHILTIUPAN", departmentId: "05" },
  { value: "06", label: "HUIZÚCAR", departmentId: "05" },
  { value: "07", label: "JAYAQUE", departmentId: "05" },
  { value: "08", label: "JICALAPA", departmentId: "05" },
  { value: "09", label: "LA LIBERTAD", departmentId: "05" },
  { value: "10", label: "NUEVO CUSCATLÁN", departmentId: "05" },
  { value: "11", label: "SANTA TECLA", departmentId: "05" },
  { value: "12", label: "QUEZALTEPEQUE", departmentId: "05" },
  { value: "13", label: "SACACOYO", departmentId: "05" },
  { value: "14", label: "SN J VILLANUEVA", departmentId: "05" },
  { value: "15", label: "SAN JUAN OPICO", departmentId: "05" },
  { value: "16", label: "SAN MATÍAS", departmentId: "05" },
  { value: "17", label: "SAN P TACACHICO", departmentId: "05" },
  { value: "18", label: "TAMANIQUE", departmentId: "05" },
  { value: "19", label: "TALNIQUE", departmentId: "05" },
  { value: "20", label: "TEOTEPEQUE", departmentId: "05" },
  { value: "21", label: "TEPECOYO", departmentId: "05" },
  { value: "22", label: "ZARAGOZA", departmentId: "05" },
  // San Salvador
  { value: "01", label: "AGUILARES", departmentId: "06" },
  { value: "02", label: "APOPA", departmentId: "06" },
  { value: "03", label: "AYUTUXTEPEQUE", departmentId: "06" },
  { value: "04", label: "CUSCATANCINGO", departmentId: "06" },
  { value: "05", label: "EL PAISNAL", departmentId: "06" },
  { value: "06", label: "GUAZAPA", departmentId: "06" },
  { value: "07", label: "ILOPANGO", departmentId: "06" },
  { value: "08", label: "MEJICANOS", departmentId: "06" },
  { value: "09", label: "NEJAPA", departmentId: "06" },
  { value: "10", label: "PANCHIMALCO", departmentId: "06" },
  { value: "11", label: "ROSARIO DE MORA", departmentId: "06" },
  { value: "12", label: "SAN MARCOS", departmentId: "06" },
  { value: "13", label: "SAN MARTIN", departmentId: "06" },
  { value: "14", label: "SAN SALVADOR", departmentId: "06" },
  { value: "15", label: "STG TEXACUANGOS", departmentId: "06" },
  { value: "16", label: "SANTO TOMAS", departmentId: "06" },
  { value: "17", label: "SOYAPANGO", departmentId: "06" },
  { value: "18", label: "TONACATEPEQUE", departmentId: "06" },
  { value: "19", label: "CIUDAD DELGADO", departmentId: "06" },
  // Cuscatlán
  { value: "01", label: "CANDELARIA", departmentId: "07" },
  { value: "02", label: "COJUTEPEQUE", departmentId: "07" },
  { value: "03", label: "EL CARMEN", departmentId: "07" },
  { value: "04", label: "EL ROSARIO", departmentId: "07" },
  { value: "05", label: "MONTE SAN JUAN", departmentId: "07" },
  { value: "06", label: "ORAT CONCEPCIÓN", departmentId: "07" },
  { value: "07", label: "SAN B PERULAPIA", departmentId: "07" },
  { value: "08", label: "SAN CRISTÓBAL", departmentId: "07" },
  { value: "09", label: "SAN J GUAYABAL", departmentId: "07" },
  { value: "10", label: "SAN P PERULAPÁN", departmentId: "07" },
  { value: "11", label: "SAN RAF CEDROS", departmentId: "07" },
  { value: "12", label: "SAN RAMON", departmentId: "07" },
  { value: "13", label: "STA C ANALQUITO", departmentId: "07" },
  { value: "14", label: "STA C MICHAPA", departmentId: "07" },
  { value: "15", label: "SUCHITOTO", departmentId: "07" },
  { value: "16", label: "TENANCINGO", departmentId: "07" },
  // La Paz
  { value: "01", label: "CUYULTITÁN", departmentId: "08" },
  { value: "02", label: "EL ROSARIO", departmentId: "08" },
  { value: "03", label: "JERUSALÉN", departmentId: "08" },
  { value: "04", label: "MERCED LA CEIBA", departmentId: "08" },
  { value: "05", label: "OLOCUILTA", departmentId: "08" },
  { value: "06", label: "PARAÍSO OSORIO", departmentId: "08" },
  { value: "07", label: "SN ANT MASAHUAT", departmentId: "08" },
  { value: "08", label: "SAN EMIGDIO", departmentId: "08" },
  { value: "09", label: "SN FCO CHINAMEC", departmentId: "08" },
  { value: "10", label: "SAN J NONUALCO", departmentId: "08" },
  { value: "11", label: "SAN JUAN TALPA", departmentId: "08" },
  { value: "12", label: "SAN JUAN TEPEZONTES", departmentId: "08" },
  { value: "13", label: "SAN LUIS TALPA", departmentId: "08" },
  { value: "14", label: "SAN MIGUEL TEPEZONTES", departmentId: "08" },
  { value: "15", label: "SAN PEDRO MASAHUAT", departmentId: "08" },
  { value: "16", label: "SAN PEDRO NONUALCO", departmentId: "08" },
  { value: "17", label: "SAN R OBRAJUELO", departmentId: "08" },
  { value: "18", label: "STA MA OSTUMA", departmentId: "08" },
  { value: "19", label: "STGO NONUALCO", departmentId: "08" },
  { value: "20", label: "TAPALHUACA", departmentId: "08" },
  { value: "21", label: "ZACATECOLUCA", departmentId: "08" },
  { value: "22", label: "SN LUIS LA HERR", departmentId: "08" },
  // Cabañas
  { value: "01", label: "CINQUERA", departmentId: "09" },
  { value: "02", label: "GUACOTECTI", departmentId: "09" },
  { value: "03", label: "ILOBASCO", departmentId: "09" },
  { value: "04", label: "JUTIAPA", departmentId: "09" },
  { value: "05", label: "SAN ISIDRO", departmentId: "09" },
  { value: "06", label: "SENSUNTEPEQUE", departmentId: "09" },
  { value: "07", label: "TEJUTEPEQUE", departmentId: "09" },
  { value: "08", label: "VICTORIA", departmentId: "09" },
  { value: "09", label: "DOLORES", departmentId: "09" },
  // San Vicente
  { value: "01", label: "APASTEPEQUE", departmentId: "10" },
  { value: "02", label: "GUADALUPE", departmentId: "10" },
  { value: "03", label: "SAN CAY ISTEPEQ", departmentId: "10" },
  { value: "04", label: "SANTA CLARA", departmentId: "10" },
  { value: "05", label: "SANTO DOMINGO", departmentId: "10" },
  { value: "06", label: "SN EST CATARINA", departmentId: "10" },
  { value: "07", label: "SAN ILDEFONSO", departmentId: "10" },
  { value: "08", label: "SAN LORENZO", departmentId: "10" },
  { value: "09", label: "SAN SEBASTIÁN", departmentId: "10" },
  { value: "10", label: "SAN VICENTE", departmentId: "10" },
  { value: "11", label: "TECOLUCA", departmentId: "10" },
  { value: "12", label: "TEPETITÁN", departmentId: "10" },
  { value: "13", label: "VERAPAZ", departmentId: "10" },
  // Usulután
  { value: "01", label: "ALEGRÍA", departmentId: "11" },
  { value: "02", label: "BERLÍN", departmentId: "11" },
  { value: "03", label: "CALIFORNIA", departmentId: "11" },
  { value: "04", label: "CONCEP BATRES", departmentId: "11" },
  { value: "05", label: "EL TRIUNFO", departmentId: "11" },
  { value: "06", label: "EREGUAYQUÍN", departmentId: "11" },
  { value: "07", label: "ESTANZUELAS", departmentId: "11" },
  { value: "08", label: "JIQUILISCO", departmentId: "11" },
  { value: "09", label: "JUCUAPA", departmentId: "11" },
  { value: "10", label: "JUCUARÁN", departmentId: "11" },
  { value: "11", label: "MERCEDES UMAÑA", departmentId: "11" },
  { value: "12", label: "NUEVA GRANADA", departmentId: "11" },
  { value: "13", label: "OZATLÁN", departmentId: "11" },
  { value: "14", label: "PTO EL TRIUNFO", departmentId: "11" },
  { value: "15", label: "SAN AGUSTÍN", departmentId: "11" },
  { value: "16", label: "SN BUENAVENTURA", departmentId: "11" },
  { value: "17", label: "SAN DIONISIO", departmentId: "11" },
  { value: "18", label: "SANTA ELENA", departmentId: "11" },
  { value: "19", label: "SAN FCO JAVIER", departmentId: "11" },
  { value: "20", label: "SANTA MARÍA", departmentId: "11" },
  { value: "21", label: "STGO DE MARÍA", departmentId: "11" },
  { value: "22", label: "TECAPÁN", departmentId: "11" },
  { value: "23", label: "USULUTÁN", departmentId: "11" },
  // San Miguel
  { value: "01", label: "CAROLINA", departmentId: "12" },
  { value: "02", label: "CIUDAD BARRIOS", departmentId: "12" },
  { value: "03", label: "COMACARÁN", departmentId: "12" },
  { value: "04", label: "CHAPELTIQUE", departmentId: "12" },
  { value: "05", label: "CHINAMECA", departmentId: "12" },
  { value: "06", label: "CHIRILAGUA", departmentId: "12" },
  { value: "07", label: "EL TRANSITO", departmentId: "12" },
  { value: "08", label: "LOLOTIQUE", departmentId: "12" },
  { value: "09", label: "MONCAGUA", departmentId: "12" },
  { value: "10", label: "NUEVA GUADALUPE", departmentId: "12" },
  { value: "11", label: "NVO EDÉN S JUAN", departmentId: "12" },
  { value: "12", label: "QUELEPA", departmentId: "12" },
  { value: "13", label: "SAN ANT D MOSCO", departmentId: "12" },
  { value: "14", label: "SAN GERARDO", departmentId: "12" },
  { value: "15", label: "SAN JORGE", departmentId: "12" },
  { value: "16", label: "SAN LUIS REINA", departmentId: "12" },
  { value: "17", label: "SAN MIGUEL", departmentId: "12" },
  { value: "18", label: "SAN RAF ORIENTE", departmentId: "12" },
  { value: "19", label: "SESORI", departmentId: "12" },
  { value: "20", label: "ULUAZAPA", departmentId: "12" },
  // Morazán
  { value: "01", label: "ARAMBALA", departmentId: "13" },
  { value: "02", label: "CACAOPERA", departmentId: "13" },
  { value: "03", label: "CORINTO", departmentId: "13" },
  { value: "04", label: "CHILANGA", departmentId: "13" },
  { value: "05", label: "DELIC DE CONCEP", departmentId: "13" },
  { value: "06", label: "EL DIVISADERO", departmentId: "13" },
  { value: "07", label: "EL ROSARIO", departmentId: "13" },
  { value: "08", label: "GUALOCOCTI", departmentId: "13" },
  { value: "09", label: "GUATAJIAGUA", departmentId: "13" },
  { value: "10", label: "JOATECA", departmentId: "13" },
  { value: "11", label: "JOCOAITIQUE", departmentId: "13" },
  { value: "12", label: "JOCORO", departmentId: "13" },
  { value: "13", label: "LOLOTIQUILLO", departmentId: "13" },
  { value: "14", label: "MEANGUERA", departmentId: "13" },
  { value: "15", label: "OSICALA", departmentId: "13" },
  { value: "16", label: "PERQUÍN", departmentId: "13" },
  { value: "17", label: "SAN CARLOS", departmentId: "13" },
  { value: "18", label: "SAN FERNANDO", departmentId: "13" },
  { value: "19", label: "SAN FCO GOTERA", departmentId: "13" },
  { value: "20", label: "SAN ISIDRO", departmentId: "13" },
  { value: "21", label: "SAN SIMÓN", departmentId: "13" },
  { value: "22", label: "SENSEMBRA", departmentId: "13" },
  { value: "23", label: "SOCIEDAD", departmentId: "13" },
  { value: "24", label: "TOROLA", departmentId: "13" },
  { value: "25", label: "YAMABAL", departmentId: "13" },
  { value: "26", label: "YOLOAIQUÍN", departmentId: "13" },
  // La Unión
  { value: "01", label: "ANAMOROS", departmentId: "14" },
  { value: "02", label: "BOLÍVAR", departmentId: "14" },
  { value: "03", label: "CONCEP DE OTE", departmentId: "14" },
  { value: "04", label: "CONCHAGUA", departmentId: "14" },
  { value: "05", label: "EL CARMEN", departmentId: "14" },
  { value: "06", label: "EL SAUCE", departmentId: "14" },
  { value: "07", label: "INTIPUCÁ", departmentId: "14" },
  { value: "08", label: "LA UNIÓN", departmentId: "14" },
  { value: "09", label: "LISLIQUE", departmentId: "14" },
  { value: "10", label: "MEANG DEL GOLFO", departmentId: "14" },
  { value: "11", label: "NUEVA ESPARTA", departmentId: "14" },
  { value: "12", label: "PASAQUINA", departmentId: "14" },
  { value: "13", label: "POLORÓS", departmentId: "14" },
  { value: "14", label: "SAN ALEJO", departmentId: "14" },
  { value: "15", label: "SAN JOSE", departmentId: "14" },
  { value: "16", label: "SANTA ROSA LIMA", departmentId: "14" },
  { value: "17", label: "YAYANTIQUE", departmentId: "14" },
  { value: "18", label: "YUCUAIQUÍN", departmentId: "14" },
];