export const measurementUnits = [
  { value: 1, label: "metro" },
  { value: 2, label: "Yarda 1" },
  { value: 6, label: "milímetro" },
  { value: 9, label: "kilómetro cuadrado" },
  { value: 10, label: "Hectárea" },
  { value: 13, label: "metro cuadrado" },
  { value: 15, label: "Vara cuadrada 2" },
  { value: 18, label: "metro cúbico" },
  { value: 20, label: "Barril 3" },
  { value: 22, label: "Galón 1, 4" },
  { value: 23, label: "Litro" },
  { value: 24, label: "Botella" },
  { value: 26, label: "Mililitro" },
  { value: 30, label: "Tonelada" },
  { value: 32, label: "Quintal 1" },
  { value: 33, label: "Arroba 1" },
  { value: 34, label: "Kilogramo" },
  { value: 36, label: "Libra 1" },
  { value: 37, label: "Onza troy 5" },
  { value: 38, label: "Onza 1" },
  { value: 39, label: "Gramo" },
  { value: 40, label: "Miligramo" },
  { value: 42, label: "Megawatt" },
  { value: 43, label: "Kilowatt" },
  { value: 44, label: "Watt" },
  { value: 45, label: "Megavoltio-amperio" },
  { value: 46, label: "Kilovoltio-amperio" },
  { value: 47, label: "Voltio-amperio" },
  { value: 49, label: "Gigawatt-hora" },
  { value: 50, label: "Megawatt-hora" },
  { value: 51, label: "Kilowatt-hora" },
  { value: 52, label: "Watt-hora" },
  { value: 53, label: "Kilovoltio" },
  { value: 54, label: "Voltio" },
  { value: 55, label: "Millar" },
  { value: 56, label: "Medio millar" },
  { value: 57, label: "Ciento" },
  { value: 58, label: "Docena" },
  { value: 59, label: "Unidad" },
  { value: 99, label: "Otra 6" },
];