export const zones = [
  { value: "00", label: "Otro (Para extranjeros)", departmentId: "00" },
  { value: "13", label: "AHUACHAPAN NORTE", departmentId: "01" },
  { value: "14", label: "AHUACHAPAN CENTRO", departmentId: "01" },
  { value: "15", label: "AHUACHAPAN SUR", departmentId: "01" },
  { value: "14", label: "SANTA ANA NORTE", departmentId: "02" },
  { value: "15", label: "SANTA ANA CENTRO", departmentId: "02" },
  { value: "16", label: "SANTA ANA ESTE", departmentId: "02" },
  { value: "17", label: "SANTA ANA OESTE", departmentId: "02" },
  { value: "17", label: "SONSONATE NORTE", departmentId: "03" },
  { value: "18", label: "SONSONATE CENTRO", departmentId: "03" },
  { value: "19", label: "SONSONATE ESTE", departmentId: "03" },
  { value: "20", label: "SONSONATE OESTE", departmentId: "03" },
  { value: "34", label: "CHALATENANGO NORTE", departmentId: "04" },
  { value: "35", label: "CHALATENANGO CENTRO", departmentId: "04" },
  { value: "36", label: "CHALATENANGO SUR", departmentId: "04" },
  { value: "23", label: "LA LIBERTAD NORTE", departmentId: "05" },
  { value: "24", label: "LA LIBERTAD CENTRO", departmentId: "05" },
  { value: "25", label: "LA LIBERTAD OESTE", departmentId: "05" },
  { value: "26", label: "LA LIBERTAD ESTE", departmentId: "05" },
  { value: "27", label: "LA LIBERTAD COSTA", departmentId: "05" },
  { value: "28", label: "LA LIBERTAD SUR", departmentId: "05" },
  { value: "20", label: "SAN SALVADOR NORTE", departmentId: "06" },
  { value: "21", label: "SAN SALVADOR OESTE", departmentId: "06" },
  { value: "22", label: "SAN SALVADOR ESTE", departmentId: "06" },
  { value: "23", label: "SAN SALVADOR CENTRO", departmentId: "06" },
  { value: "24", label: "SAN SALVADOR SUR", departmentId: "06" },
  { value: "17", label: "CUSCATLAN NORTE", departmentId: "07" },
  { value: "18", label: "CUSCATLAN SUR", departmentId: "07" },
  { value: "23", label: "LA PAZ OESTE", departmentId: "08" },
  { value: "24", label: "LA PAZ CENTRO", departmentId: "08" },
  { value: "25", label: "LA PAZ ESTE", departmentId: "08" },
  { value: "10", label: "CABAÑAS OESTE", departmentId: "09" },
  { value: "11", label: "CABAÑAS ESTE", departmentId: "09" },
  { value: "14", label: "SAN VICENTE NORTE", departmentId: "10" },
  { value: "15", label: "SAN VICENTE SUR", departmentId: "10" },
  { value: "24", label: "USULUTAN NORTE", departmentId: "11" },
  { value: "25", label: "USULUTAN ESTE", departmentId: "11" },
  { value: "26", label: "USULUTAN OESTE", departmentId: "11" },
  { value: "21", label: "SAN MIGUEL NORTE", departmentId: "12" },
  { value: "22", label: "SAN MIGUEL CENTRO", departmentId: "12" },
  { value: "23", label: "SAN MIGUEL OESTE", departmentId: "12" },
  { value: "27", label: "MORAZAN NORTE", departmentId: "13" },
  { value: "28", label: "MORAZAN SUR", departmentId: "13" },
  { value: "19", label: "LA UNION NORTE", departmentId: "14" },
  { value: "20", label: "LA UNION SUR", departmentId: "14" },
];